"""Writes tests/validation/webp_media_vectors.cpp from the files that
make_webp_media_vectors.sh made.

Usage: python3 embed_webp_media_vectors.py <output .cpp> <directory>
"""

import os
import sys

MAX_VECTOR = 64 * 1024

out_path, directory = sys.argv[1], sys.argv[2]
files = []
for name in sorted(os.listdir(directory)):
    if not name.endswith(".webp"):
        continue
    with open(os.path.join(directory, name), "rb") as f:
        data = f.read()
    if len(data) > MAX_VECTOR:
        sys.exit(f"{name} is larger than {MAX_VECTOR} bytes; vectors must stay small")
    files.append((name, data))

lines = [
    "// Generated by tests/reference/embed_webp_media_vectors.py from the output of",
    "// tests/reference/make_webp_media_vectors.sh (libwebp 1.3.2 cwebp). Do not edit.",
    "",
    '#include "validation/webp_media_vectors.hpp"',
    "",
    "#include <array>",
    "#include <cstdlib>",
    "",
    "namespace recovery::test::webp_vectors {",
    "",
    "namespace {",
    "",
]
for index, (name, data) in enumerate(files):
    lines.append(f"// {name}")
    lines.append(f"constexpr std::array<std::uint8_t, {len(data)}> kVector{index} = {{")
    for start in range(0, len(data), 16):
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in data[start:start + 16]) + ",")
    lines.append("};")
    lines.append("")
lines += [
    "}  // namespace",
    "",
    "const std::vector<Vector>& all() {",
    "    static const std::vector<Vector> vectors = {",
]
for index, (name, _) in enumerate(files):
    lines.append(f'        {{"{name}", kVector{index}}},')
lines += [
    "    };",
    "    return vectors;",
    "}",
    "",
    "const Vector& named(std::string_view name) {",
    "    for (const Vector& vector : all()) {",
    "        if (vector.name == name) {",
    "            return vector;",
    "        }",
    "    }",
    "    std::abort();",
    "}",
    "",
    "}  // namespace recovery::test::webp_vectors",
]
with open(out_path, "w", newline="\n") as f:
    f.write("\n".join(lines) + "\n")
print(f"{len(files)} vectors")
