"""Writes tests/support/audio_samples.cpp from directories of small audio
files made by independent encoders (make_audio_samples.sh and
make_audio_samples.ps1).

Usage: python3 embed_audio_samples.py <output .cpp> <directory>...
"""

import os
import sys

FORMATS = {".mp3": "mp3", ".wav": "wav", ".m4a": "m4a", ".aac": "aac"}
PRODUCERS = {
    "lame": "LAME 3.100",
    "ffmpeg": "FFmpeg 6.1.1",
    "faac": "FAAC 1.30",
    "fdkaac": "fdkaac 1.0.0 (Fraunhofer FDK AAC 2.0.2)",
    "sox": "SoX 14.4.2",
    "python": "Python 3.12 wave",
    "speech": "Windows speech synthesizer (System.Speech)",
    "mediafoundation": "Windows Media Foundation",
}
MAX_SAMPLE = 16384

out_path = sys.argv[1]
files = []
for directory in sys.argv[2:]:
    for name in sorted(os.listdir(directory)):
        stem, ext = os.path.splitext(name)
        if ext not in FORMATS:
            continue
        with open(os.path.join(directory, name), "rb") as f:
            data = f.read()
        if len(data) > MAX_SAMPLE:
            sys.exit(f"{name} is larger than {MAX_SAMPLE} bytes; samples must stay small")
        files.append((name, FORMATS[ext], PRODUCERS[stem.split("_")[0]], data))
files.sort()

lines = [
    "// Generated by tests/reference/embed_audio_samples.py from the output of",
    "// tests/reference/make_audio_samples.sh and make_audio_samples.ps1. Do not edit.",
    "",
    '#include "support/audio_samples.hpp"',
    "",
    "#include <array>",
    "#include <cstdlib>",
    "",
    "namespace recovery::test::audio_samples {",
    "",
    "namespace {",
    "",
]
for index, (name, _, _, data) in enumerate(files):
    lines.append(f"// {name}")
    lines.append(f"constexpr std::array<std::uint8_t, {len(data)}> kSample{index} = {{")
    for start in range(0, len(data), 16):
        chunk = ", ".join(f"0x{b:02X}" for b in data[start:start + 16])
        lines.append(f"    {chunk},")
    lines.append("};")
    lines.append("")
lines.append("}  // namespace")
lines.append("")
lines.append("const std::vector<Sample>& all() {")
lines.append("    static const std::vector<Sample> samples = {")
for index, (name, fmt, producer, _) in enumerate(files):
    lines.append(f'        {{"{name}", "{fmt}", "{producer}", kSample{index}}},')
lines.append("    };")
lines.append("    return samples;")
lines.append("}")
lines.append("")
lines.append("const Sample& named(std::string_view name) {")
lines.append("    for (const Sample& sample : all()) {")
lines.append("        if (sample.name == name) {")
lines.append("            return sample;")
lines.append("        }")
lines.append("    }")
lines.append("    std::abort();")
lines.append("}")
lines.append("")
lines.append("}  // namespace recovery::test::audio_samples")
lines.append("")

with open(out_path, "w", newline="\n") as f:
    f.write("\n".join(lines))
print(f"{len(files)} samples, {sum(len(d) for *_, d in files)} bytes")
