"""Writes a generated .cpp that embeds the files of a directory as test
vectors for the media decoder tests (the files that a make_*_media_vectors.sh
script made).

Usage: python3 embed_media_vectors.py <output .cpp> <header> <namespace> <extension> <directory> [producer]

The header (relative to tests/, such as validation/aac_media_vectors.hpp)
declares, in namespace recovery::test::<namespace>, a struct Vector with
`name` and `bytes`, all() and named(), as webp_media_vectors.hpp does.
"""

import os
import sys

MAX_VECTOR = 64 * 1024

out_path, header, namespace, extension, directory = sys.argv[1:6]
producer = sys.argv[6] if len(sys.argv) > 6 else None
script = os.path.basename(out_path).replace("_media_vectors.cpp", "")
files = []
for name in sorted(os.listdir(directory)):
    if not name.endswith("." + extension):
        continue
    with open(os.path.join(directory, name), "rb") as f:
        data = f.read()
    if len(data) > MAX_VECTOR:
        sys.exit(f"{name} is larger than {MAX_VECTOR} bytes; vectors must stay small")
    files.append((name, data))

note = f"// tests/reference/make_{script}_media_vectors.sh"
if producer:
    note += f" ({producer})"
lines = [
    "// Generated by tests/reference/embed_media_vectors.py from the output of",
    note + ". Do not edit.",
    "",
    f'#include "{header}"',
    "",
    "#include <array>",
    "#include <cstdlib>",
    "",
    f"namespace recovery::test::{namespace} {{",
    "",
    "namespace {",
    "",
]
for index, (name, data) in enumerate(files):
    lines.append(f"// {name}")
    lines.append(f"constexpr std::array<std::uint8_t, {len(data)}> kVector{index} = {{")
    for start in range(0, len(data), 16):
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in data[start:start + 16]) + ",")
    lines.append("};")
    lines.append("")
lines += [
    "}  // namespace",
    "",
    "const std::vector<Vector>& all() {",
    "    static const std::vector<Vector> vectors = {",
]
for index, (name, _) in enumerate(files):
    lines.append(f'        {{"{name}", kVector{index}}},')
lines += [
    "    };",
    "    return vectors;",
    "}",
    "",
    "const Vector& named(std::string_view name) {",
    "    for (const Vector& vector : all()) {",
    "        if (vector.name == name) {",
    "            return vector;",
    "        }",
    "    }",
    "    std::abort();",
    "}",
    "",
    f"}}  // namespace recovery::test::{namespace}",
]
with open(out_path, "w", newline="\n") as f:
    f.write("\n".join(lines) + "\n")
print(f"{len(files)} vectors")
