"""Writes tests/support/image_samples.cpp from directories of small image
files made by independent encoders (make_image_samples.sh and
make_image_samples.ps1).

Usage: python3 embed_image_samples.py <output .cpp> <directory>...
"""

import os
import sys

FORMATS = {".jpg": "jpeg", ".png": "png", ".webp": "webp", ".gif": "gif", ".bmp": "bmp"}
PRODUCERS = {
    "cjpeg": "libjpeg-turbo 2.1.5 cjpeg",
    "jpegtran": "libjpeg-turbo 2.1.5 jpegtran",
    "djpeg": "libjpeg-turbo 2.1.5 djpeg",
    "cwebp": "libwebp 1.3.2 cwebp",
    "dwebp": "libwebp 1.3.2 dwebp",
    "webpmux": "libwebp 1.3.2 webpmux",
    "img2webp": "libwebp 1.3.2 img2webp",
    "giflib": "giflib 5.2 gif2rgb",
    "gdiplus": "Windows GDI+",
}
MAX_SAMPLE = 4096

out_path = sys.argv[1]
files = []
for directory in sys.argv[2:]:
    for name in sorted(os.listdir(directory)):
        stem, ext = os.path.splitext(name)
        if ext not in FORMATS:
            continue
        with open(os.path.join(directory, name), "rb") as f:
            data = f.read()
        if len(data) > MAX_SAMPLE:
            sys.exit(f"{name} is larger than {MAX_SAMPLE} bytes; samples must stay small")
        files.append((name, FORMATS[ext], PRODUCERS[stem.split("_")[0]], data))
files.sort()

lines = [
    "// Generated by tests/reference/embed_image_samples.py from the output of",
    "// tests/reference/make_image_samples.sh and make_image_samples.ps1. Do not edit.",
    "",
    '#include "support/image_samples.hpp"',
    "",
    "#include <array>",
    "#include <cstdlib>",
    "",
    "namespace recovery::test::samples {",
    "",
    "namespace {",
    "",
]
for index, (name, _, _, data) in enumerate(files):
    lines.append(f"// {name}")
    lines.append(f"constexpr std::array<std::uint8_t, {len(data)}> kSample{index} = {{")
    for start in range(0, len(data), 16):
        chunk = ", ".join(f"0x{b:02X}" for b in data[start:start + 16])
        lines.append(f"    {chunk},")
    lines.append("};")
    lines.append("")
lines.append("}  // namespace")
lines.append("")
lines.append("const std::vector<Sample>& all() {")
lines.append("    static const std::vector<Sample> samples = {")
for index, (name, fmt, producer, _) in enumerate(files):
    lines.append(f'        {{"{name}", "{fmt}", "{producer}", kSample{index}}},')
lines.append("    };")
lines.append("    return samples;")
lines.append("}")
lines.append("")
lines.append("const Sample& named(std::string_view name) {")
lines.append("    for (const Sample& sample : all()) {")
lines.append("        if (sample.name == name) {")
lines.append("            return sample;")
lines.append("        }")
lines.append("    }")
lines.append("    std::abort();")
lines.append("}")
lines.append("")
lines.append("}  // namespace recovery::test::samples")
lines.append("")

with open(out_path, "w", newline="\n") as f:
    f.write("\n".join(lines))
print(f"{len(files)} samples, {sum(len(d) for *_, d in files)} bytes")
