"""Writes tests/support/mp4_samples.cpp from directories of small MP4 files
made by independent writers (make_mp4_samples.sh and make_mp4_samples.ps1).

For every file it records what FFmpeg's demuxer finds, as the expectation
for the parser: each track's kind and codec, its size or channels and rate,
its number of samples, and an FNV-1a hash of every sample's offset and size
in order (ffprobe -show_packets with edit lists ignored, so every sample of
the sample tables is listed). The samples of fragmented files are those of
moov's tables and of every movie fragment (the parser reads fragments since
P12).

Usage (in WSL, with ffprobe on PATH):
    python3 embed_mp4_samples.py <output .cpp> <directory>...
"""

import json
import os
import struct
import subprocess
import sys

EXTENSIONS = {".mp4", ".mov", ".m4v", ".3gp"}
PRODUCERS = {
    "ffmpeg": "FFmpeg 6.1.1",
    "gpac": "GPAC MP4Box 2.2.1",
    "mediafoundation": "Windows Media Foundation",
}
MAX_SAMPLE = 16384
FNV_OFFSET = 0xCBF29CE484222325
FNV_PRIME = 0x100000001B3


def fnv1a(value, data):
    for byte in data:
        value ^= byte
        value = (value * FNV_PRIME) & 0xFFFFFFFFFFFFFFFF
    return value


def top_level_types(data):
    types = []
    position = 0
    while len(data) - position >= 8:
        size, kind = struct.unpack(">I4s", data[position:position + 8])
        if size == 1:
            size = struct.unpack(">Q", data[position + 8:position + 16])[0]
        elif size == 0:
            size = len(data) - position
        if size < 8:
            break
        types.append(kind)
        position += size
    return types


def probe(path):
    output = subprocess.run(
        ["ffprobe", "-v", "error", "-ignore_editlist", "1", "-show_streams", "-show_packets", "-of", "json", path],
        check=True, capture_output=True, text=True).stdout
    report = json.loads(output)
    tracks = []
    for stream in sorted(report["streams"], key=lambda s: s["index"]):
        kind = {"video": "video", "audio": "audio"}.get(stream["codec_type"], "other")
        tracks.append({
            "kind": kind,
            "codec": stream.get("codec_tag_string", ""),
            "width": int(stream.get("width", 0)) if kind == "video" else 0,
            "height": int(stream.get("height", 0)) if kind == "video" else 0,
            "channels": int(stream.get("channels", 0)) if kind == "audio" else 0,
            "rate": int(stream.get("sample_rate", 0)) if kind == "audio" else 0,
            "samples": 0,
            "hash": FNV_OFFSET,
        })
    for packet in report.get("packets", []):
        track = tracks[packet["stream_index"]]
        track["samples"] += 1
        track["hash"] = fnv1a(track["hash"], struct.pack("<QI", int(packet["pos"]), int(packet["size"])))
    return tracks


out_path = sys.argv[1]
files = []
for directory in sys.argv[2:]:
    for name in sorted(os.listdir(directory)):
        stem, ext = os.path.splitext(name)
        if ext not in EXTENSIONS:
            continue
        path = os.path.join(directory, name)
        with open(path, "rb") as f:
            data = f.read()
        if len(data) > MAX_SAMPLE:
            sys.exit(f"{name} is larger than {MAX_SAMPLE} bytes; samples must stay small")
        fragmented = b"moof" in top_level_types(data)
        files.append((name, PRODUCERS[stem.split("_")[0]], data, fragmented, probe(path)))
files.sort()

lines = [
    "// Generated by tests/reference/embed_mp4_samples.py from the output of",
    "// tests/reference/make_mp4_samples.sh and make_mp4_samples.ps1. Do not edit.",
    "",
    '#include "support/mp4_samples.hpp"',
    "",
    "#include <array>",
    "#include <cstdlib>",
    "",
    "namespace recovery::test::mp4_samples {",
    "",
    "namespace {",
    "",
]
for index, (name, _, data, fragmented, tracks) in enumerate(files):
    lines.append(f"// {name}")
    lines.append(f"constexpr std::array<std::uint8_t, {len(data)}> kSample{index} = {{")
    for start in range(0, len(data), 16):
        chunk = ", ".join(f"0x{b:02X}" for b in data[start:start + 16])
        lines.append(f"    {chunk},")
    lines.append("};")
    lines.append(f"constexpr std::array<Track, {len(tracks)}> kTracks{index} = {{{{")
    for track in tracks:
        lines.append(f'    {{"{track["kind"]}", "{track["codec"]}", {track["width"]}, {track["height"]}, '
                     f'{track["channels"]}, {track["rate"]}, {track["samples"]}, 0x{track["hash"]:016X}ULL}},')
    lines.append("}};")
    lines.append("")
lines.append("}  // namespace")
lines.append("")
lines.append("const std::vector<Sample>& all() {")
lines.append("    static const std::vector<Sample> samples = {")
for index, (name, producer, _, fragmented, _) in enumerate(files):
    lines.append(f'        {{"{name}", "{producer}", kSample{index}, {str(fragmented).lower()}, kTracks{index}}},')
lines.append("    };")
lines.append("    return samples;")
lines.append("}")
lines.append("")
lines.append("const Sample& named(std::string_view name) {")
lines.append("    for (const Sample& sample : all()) {")
lines.append("        if (sample.name == name) {")
lines.append("            return sample;")
lines.append("        }")
lines.append("    }")
lines.append("    std::abort();")
lines.append("}")
lines.append("")
lines.append("}  // namespace recovery::test::mp4_samples")
lines.append("")

with open(out_path, "w", newline="\n") as f:
    f.write("\n".join(lines))
print(f"wrote {len(files)} samples to {out_path}")
